[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D -e
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:code-server]
command=/usr/bin/code-server --auth none --bind-addr 0.0.0.0:3001 /home/coder/workspace
user=coder
environment=HOME="/home/coder",USER="coder",LOGNAME="coder"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
