version: "3.9"

services:
    profilarr:
        image: santiagosayshey/profilarr:latest
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TZ}
        volumes:
            - profilarr_config:/config
        networks:
            - traefik-public
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.profilarr.rule=Host(`profilarr.${BASE_DOMAIN}`)"
                - "traefik.http.routers.profilarr.entrypoints=websecure"
                - "traefik.http.routers.profilarr.tls.certresolver=dns"
                - "traefik.http.services.profilarr.loadbalancer.server.port=6868"
                - "traefik.swarm.network=traefik-public"
                - "homepage.group=Downloads"
                - "homepage.name=Profilarr"
                - "homepage.icon=profilarr.png"
                - "homepage.href=https://profilarr.${BASE_DOMAIN}/"
                - "homepage.description=Profile Management for Arr Services"

networks:
    traefik-public:
        external: true

volumes:
    profilarr_config:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "/mnt/iscsi/media-apps/profilarr"
