# ansible/roles/dns/tasks/add-machine-records.yml
---
- name: Add machine records to primary DNS
  ansible.builtin.include_tasks: "adapters/{{ primary_dns_type }}/add-machine-records.yml"

- name: Add machine records to secondary DNS
  ansible.builtin.include_tasks: "adapters/{{ secondary_dns_type }}/add-machine-records.yml"
  when: secondary_dns_enabled | bool
