name: Lint and Test pipeline

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    lint:
        name: Lint & Static Analysis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true

            - name: Install Task
              uses: arduino/setup-task@v1
              with:
                  version: 3.x
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install dependencies
              run: task install

            - name: Run linting
              run: task lint

            - name: Run static analysis
              run: task static-analysis
